version: "3"

services:
  node_server:
    build: ./backend
    container_name: node_server
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.70' 
          memory: 2048M
        reservations:
          cpus: '0.35' 
          memory: 1024M
    environment:
      - MONGO_DB_URL=mongodb://root:root@mongo:27017/admin
      - SEQ_URL=http://seq:5341
      - SERVER_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - mongo
      - mysql
    ports:
      - 3001:3001
    networks:
      - monitoring-inside-network

  vue_client:
    build: ./vue-client
    container_name: vue_client
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4' 
          memory: 1048M
        reservations:
          cpus: '0.25' 
          memory: 512M
    depends_on:
      - mongo
      - mysql
      - node_server
    ports:
      - 8081:80
    networks:
      - monitoring-inside-network

  mysql:
    container_name: mysql_db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.50'         
          memory: 1024M
        reservations:
          cpus: '0.25'          
          memory: 512M
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - monitoring-inside-network

  mongo:
    container_name: mongo_db
    image: mongo:4.4
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'  
          memory: 1024M
        reservations:
          cpus: '0.25'  
          memory: 512M
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - monitoring-inside-network

  seq:
    image: datalust/seq:2023.1
    container_name: Seq
    deploy:
      resources:
        limits:
          cpus: '0.25'  
          memory: 512M
        reservations:
          cpus: '0.15'  
          memory: 128M
    environment:
      - ACCEPT_EULA=Y
    restart: always
    volumes:
      - seq:/data
    ports:
      - 5341:80
    networks:
      - monitoring-inside-network

volumes:
  mysql:
  mongo:
  seq:

networks:
  monitoring-inside-network:
    driver: bridge