version: "3"

services:
  node_server:
    build: ./backend
    container_name: node_server
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.70' 
          memory: 2048M
        reservations:
          cpus: '0.35' 
          memory: 1024M
    environment:
      - MONGO_DB_URL=mongodb://root:root@mongo:27017/admin
      - SEQ_URL=http://seq:5341
      - SERVER_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=mysql
      - DB_PORT=3306
    depends_on:
      - db
    ports:
      - 3001:3001
    networks:
      - starti_network

  mysql:
    container_name: mysql_db
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.50'         
          memory: 1024M
        reservations:
          cpus: '0.25'          
          memory: 512M
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - starti_network

  mongo:
    container_name: mongo_db
    image: mongo:4.4
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'  
          memory: 1024M
        reservations:
          cpus: '0.25'  
          memory: 512M
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - starti_network

volumes:
  mysql:
  mongo:

networks:
  starti_network:
    driver: bridge